import { expect } from '@playwright/test'
import { test } from './helpers/sysgrid-test'
import { createAsset, resetBrowserState } from './helpers/sysgrid'

const apiBase = process.env.PW_API_BASE || 'http://127.0.0.1:8000/api/v1'

for (const [theme, width] of [['nordic-frost-v1', 1440], ['pure-clarity', 390]] as const) {
  test(`maintenance window creation and retained cancellation in ${theme} at ${width}`, async ({ page, sysApi: request }, testInfo) => {
    await resetBrowserState(page)
    await page.setViewportSize({ width, height: 1000 })
    await request.patch(`${apiBase}/settings/user/settings`, { data: { theme } })
    await page.addInitScript(value => localStorage.setItem('sysgrid-theme', value), theme)
    const asset = await createAsset(request, { name: `Window ${theme} ${Date.now()}`, system: 'UI readiness', type: 'Physical', status: 'Active' })
    await page.goto(`/monitoring?workspace=maintenance&device_id=${asset.id}`)
    await page.getByRole('button', { name: 'New window', exact: true }).click()
    await page.getByLabel('Window title').fill('Planned maintenance test')
    await page.getByLabel('Ticket reference').fill('TEST-WINDOW-1')
    await page.getByLabel('Coordinator').fill('Test operator')
    await page.getByLabel('Start time (UTC)', { exact: true }).fill('2030-01-01T10:00')
    await page.getByLabel('End time (UTC)', { exact: true }).fill('2030-01-01T09:00')
    await page.getByRole('button', { name: 'Save window', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('End time must be after start time')
    await page.getByLabel('End time (UTC)', { exact: true }).fill('2030-01-01T11:00')
    await page.getByRole('button', { name: 'Action history', exact: true }).click()
    await page.getByRole('dialog', { name: 'Leave maintenance changes?' }).getByRole('button', { name: 'Keep editing', exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'Leave maintenance changes?' })).toHaveCount(0)
    await expect(page.getByLabel('Window title')).toHaveValue('Planned maintenance test')
    await page.locator('[data-maintenance-content]').evaluate(element => { element.scrollTop = 0 })
    await page.screenshot({ path: testInfo.outputPath('schedule.png'), animations: 'disabled' })
    await page.getByRole('button', { name: 'Save window', exact: true }).click()
    const windows = page.getByRole('heading', { name: 'Maintenance windows', exact: true }).locator('..')
    await expect(windows).toContainText('Planned maintenance test · Scheduled')
    const rows = await (await request.get(`${apiBase}/maintenance?device_id=${asset.id}`)).json()
    expect(rows).toHaveLength(1)
    expect(rows[0].start_time).toBe('2030-01-01T10:00:00')
    const windowId = rows[0].id
    await page.getByRole('button', { name: 'New plan', exact: true }).click()
    await page.getByLabel('Plan title').fill('Window-bound action')
    await page.getByLabel('Existing maintenance window (optional)').selectOption(String(windowId))
    await page.getByRole('button', { name: 'Save plan', exact: true }).click()
    await expect(page.getByRole('status').filter({ hasText: /^created ·/ })).toBeVisible()
    const actionId = new URL(page.url()).searchParams.get('action')
    const preview = await (await request.post(`${apiBase}/operational-actions/${actionId}/preview`)).json()
    expect((await request.post(`${apiBase}/operational-actions/${actionId}/confirm`, { data: { preview_token: preview.preview_token, confirmation: true } })).ok()).toBeTruthy()
    await page.getByRole('button', { name: 'Action history', exact: true }).click()
    await windows.getByRole('link', { name: 'Cancel window', exact: true }).click()
    await page.getByLabel('Cancellation reason').fill('Rescheduled after review')
    let cancelRequests = 0
    page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith(`/${windowId}/cancel`)) cancelRequests++ })
    await page.getByRole('button', { name: 'Review cancellation', exact: true }).click()
    const confirmation = page.getByRole('dialog', { name: 'Cancel this maintenance window?' })
    await confirmation.getByRole('button', { name: 'Keep window', exact: true }).click()
    expect(cancelRequests).toBe(0)
    await expect(page.getByLabel('Cancellation reason')).toHaveValue('Rescheduled after review')
    await page.getByRole('button', { name: 'Review cancellation', exact: true }).click()
    await confirmation.getByRole('button', { name: 'Cancel window', exact: true }).click()
    await expect(windows).toContainText('Planned maintenance test · Cancelled')
    await expect(windows).toContainText('Rescheduled after review')
    expect(cancelRequests).toBe(1)
    const execute = await request.post(`${apiBase}/operational-actions/${actionId}/execute`, { data: { preview_token: preview.preview_token } })
    expect(execute.status()).toBe(409)
    const action = await (await request.get(`${apiBase}/operational-actions/${actionId}`)).json()
    expect(action.maintenance_window_id).toBe(windowId)
    expect(action.attempts).toHaveLength(0)
    await page.reload()
    await expect(windows).toContainText('Planned maintenance test · Cancelled')
    await expect(windows.getByRole('link', { name: 'Cancel window', exact: true })).toHaveCount(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.locator('[data-maintenance-content]').evaluate(element => { element.scrollTop = 0 })
    await page.screenshot({ path: testInfo.outputPath('cancelled.png'), animations: 'disabled' })
    await page.getByRole('button', { name: 'New plan', exact: true }).click()
    await expect(page.getByLabel('Existing maintenance window (optional)').getByRole('option', { name: /Planned maintenance test/ })).toHaveCount(0)
  })
}

test('lost window response recovers the same request without duplicates', async ({ page, sysApi: request }) => {
  await resetBrowserState(page)
  const asset = await createAsset(request, { name: `Window retry ${Date.now()}`, system: 'UI readiness', type: 'Physical', status: 'Active' })
  await page.goto(`/monitoring?workspace=maintenance&window=new&device_id=${asset.id}`)
  await page.getByLabel('Window title').fill('Recover this window')
  await page.getByLabel('Start time (UTC)', { exact: true }).fill('2030-01-01T10:00')
  await page.getByLabel('End time (UTC)', { exact: true }).fill('2030-01-01T11:00')
  const sent: Array<{ key: string | undefined; body: string | null }> = []
  await page.route('**/api/v1/maintenance', async route => {
    if (route.request().method() !== 'POST') return route.continue()
    sent.push({ key: route.request().headers()['idempotency-key'], body: route.request().postData() })
    const response = await route.fetch()
    expect(response.ok()).toBeTruthy()
    if (sent.length === 1) await route.abort('failed')
    else await route.fulfill({ response })
  })
  await page.getByRole('button', { name: 'Save window', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('The save outcome is unknown')
  await expect(page.getByLabel('Window title')).toBeDisabled()
  await page.getByRole('button', { name: 'Recover window request', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Maintenance windows', exact: true }).locator('..')).toContainText('Recover this window · Scheduled')
  expect(sent).toHaveLength(2)
  expect(sent[0]).toEqual(sent[1])
  expect(sent[0].key).toBeTruthy()
  const rows = await (await request.get(`${apiBase}/maintenance?device_id=${asset.id}`)).json()
  expect(rows).toHaveLength(1)
})

test('a late window save respects the workspace chosen after departure', async ({ page, sysApi: request }) => {
  await resetBrowserState(page)
  const asset = await createAsset(request, { name: `Window late ${Date.now()}`, system: 'UI readiness', type: 'Physical', status: 'Active' })
  await page.goto(`/monitoring?workspace=maintenance&window=new&device_id=${asset.id}`)
  await page.getByLabel('Window title').fill('Window saved after departure')
  await page.getByLabel('Start time (UTC)', { exact: true }).fill('2030-01-01T10:00')
  await page.getByLabel('End time (UTC)', { exact: true }).fill('2030-01-01T11:00')
  let release!: () => void
  const held = new Promise<void>(resolve => { release = resolve })
  let recorded!: () => void
  const serverRecorded = new Promise<void>(resolve => { recorded = resolve })
  await page.route('**/api/v1/maintenance', async route => {
    if (route.request().method() !== 'POST') return route.continue()
    const response = await route.fetch()
    expect(response.ok()).toBeTruthy()
    recorded()
    await held
    await route.fulfill({ response })
  })
  try {
    await page.getByRole('button', { name: 'Save window', exact: true }).click()
    await serverRecorded
    await page.getByRole('button', { name: 'New plan', exact: true }).click()
    await page.getByRole('dialog', { name: 'Leave maintenance changes?' }).getByRole('button', { name: 'Discard and leave', exact: true }).click()
    await page.getByLabel('Plan title').fill('Keep this newer draft')
    const response = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/maintenance'))
    release()
    await response
    await expect(page.getByLabel('Existing maintenance window (optional)').getByRole('option', { name: /Window saved after departure/ })).toHaveCount(1)
    await expect(page.getByLabel('Plan title')).toHaveValue('Keep this newer draft')
    expect(new URL(page.url()).searchParams.get('plan')).toBe('new')
  } finally { release() }
})
