import { expect, type Page } from '@playwright/test'
import { test } from './helpers/sysgrid-test'
import { createAsset, resetBrowserState } from './helpers/sysgrid'

const apiBase = process.env.PW_API_BASE || 'http://127.0.0.1:8000/api/v1'
const state = (page: Page, name: string) => page.getByRole('status').filter({ hasText: new RegExp(`^${name} ·`) })
async function recordAction(request: any, assetId: number, parameters = {}, actionKey = 'telemetry.snapshot') {
  const response = await request.post(`${apiBase}/operational-actions`, { data: { target_device_ids: [assetId], action_key: actionKey, parameters, idempotency_key: crypto.randomUUID() } })
  expect(response.ok()).toBeTruthy()
  return response.json()
}
async function execute(page: Page) {
  await page.getByRole('button', { name: 'Execute simulation', exact: true }).click()
  await page.getByRole('dialog', { name: 'Execute this simulation?' }).getByRole('button', { name: 'Continue', exact: true }).click()
}
async function confirmPlan(page: Page) {
  await page.getByLabel('I reviewed this simulation, its targets, risk and recovery plan.').check()
  await page.getByRole('button', { name: 'Confirm reviewed plan', exact: true }).click()
  await expect(state(page, 'confirmed')).toBeVisible()
}

for (const [theme, width] of [['nordic-frost-v1', 1440], ['pure-clarity', 390]] as const) {
  test(`maintenance plan through verification and rollback in ${theme} at ${width}`, async ({ page, sysApi: request }, testInfo) => {
    await resetBrowserState(page)
    await page.setViewportSize({ width, height: 1000 })
    await request.patch(`${apiBase}/settings/user/settings`, { data: { theme } })
    await page.addInitScript(value => localStorage.setItem('sysgrid-theme', value), theme)
    const asset = await createAsset(request, { name: `Maintenance lifecycle ${theme} ${Date.now()}`, system: 'UI readiness', type: 'Physical', status: 'Active' })
    await page.goto('/monitoring')
    await page.getByRole('button', { name: 'Maintenance', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Maintenance', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'New plan', exact: true }).click()
    await page.getByLabel('Plan title').fill('Routine maintenance verification')
    await page.getByLabel('Action', { exact: false }).selectOption('telemetry.snapshot')
    await page.getByLabel('Ticket reference').fill('TEST-MAINT-1')
    await page.getByLabel('Plan owner').fill('Simulation operator')
    await page.getByLabel('Window / scheduling notes').fill('Approved test fixture window')
    await page.getByLabel('Filter loaded assets').fill(asset.name)
    await page.getByRole('checkbox', { name: new RegExp(asset.name) }).check()
    await page.getByRole('button', { name: 'Save plan', exact: true }).click()
    await expect(state(page, 'created')).toBeVisible()
    const actionId = new URL(page.url()).searchParams.get('action')
    expect(actionId).toBeTruthy()
    await page.getByRole('button', { name: 'Preview plan', exact: true }).click()
    await expect(state(page, 'previewed')).toBeVisible()
    await page.locator('[data-maintenance-content]').evaluate(element => { element.scrollTop = 0 })
    await page.getByRole('heading', { name: 'Maintenance', exact: true }).scrollIntoViewIfNeeded()
    await page.screenshot({ path: testInfo.outputPath('preview.png'), animations: 'disabled' })
    await confirmPlan(page)
    let executionRequests = 0
    page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/execute')) executionRequests++ })
    await page.getByRole('button', { name: 'Execute simulation', exact: true }).click()
    await page.getByRole('dialog', { name: 'Execute this simulation?' }).getByRole('button', { name: 'Cancel', exact: true }).click()
    expect(executionRequests).toBe(0)
    await execute(page)
    await expect(state(page, 'succeeded')).toBeVisible()
    await page.getByLabel('Outcome summary / rollback reason').fill('The recording contains the selected asset and no external effects.')
    await page.getByLabel('Evidence reference', { exact: true }).fill('test-evidence://maintenance/routine')
    await page.getByRole('button', { name: 'Record verification', exact: true }).click()
    await expect(state(page, 'verified')).toBeVisible()
    await page.getByLabel('Outcome summary / rollback reason').fill('Complete the rollback simulation exercise.')
    await page.getByRole('button', { name: 'Roll back simulation', exact: true }).click()
    await page.getByRole('dialog', { name: 'Roll back this simulation?' }).getByRole('button', { name: 'Continue', exact: true }).click()
    await expect(state(page, 'rolled back')).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Action history', exact: true })).toBeVisible()
    const record = await (await request.get(`${apiBase}/operational-actions/${actionId}`)).json()
    expect(record.execution_result.external_side_effect).toBe(false)
    expect(record.status).toBe('ROLLED_BACK')
    expect(record.attempts).toHaveLength(2)
    expect(executionRequests).toBe(1)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.locator('[data-maintenance-content]').evaluate(element => { element.scrollTop = 0 })
    await page.getByRole('heading', { name: 'Maintenance', exact: true }).scrollIntoViewIfNeeded()
    await page.screenshot({ path: testInfo.outputPath('completed.png'), animations: 'disabled' })
    await page.reload()
    await expect(state(page, 'rolled back')).toBeVisible()
  })
}

test('high-risk failure keeps recovery first class', async ({ page, sysApi: request }, testInfo) => {
  await resetBrowserState(page)
  const asset = await createAsset(request, { name: `Maintenance recovery ${Date.now()}`, system: 'UI readiness', type: 'Physical', status: 'Active' })
  const action = await recordAction(request, asset.id, { service_name: 'synthetic-service', simulation_outcome: 'failure', simulation_rollback_outcome: 'failure' }, 'service.restart')
  await page.goto(`/monitoring?workspace=maintenance&action=${action.id}`)
  await page.getByRole('button', { name: 'Preview plan', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Record authorization' })).toBeDisabled()
  await page.getByLabel('Approval reference').fill('TEST-APPROVAL-1')
  await page.getByLabel('Recovery plan reference').fill('test-runbook://maintenance/recovery')
  await page.getByRole('button', { name: 'Record authorization' }).click()
  await expect(state(page, 'authorized')).toBeVisible()
  await confirmPlan(page)
  await execute(page)
  await expect(state(page, 'failed')).toBeVisible()
  await page.getByLabel('Outcome summary / rollback reason').fill('Execution failure exercise: attempt rollback.')
  await page.getByRole('button', { name: 'Roll back simulation', exact: true }).click()
  await page.getByRole('dialog', { name: 'Roll back this simulation?' }).getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(state(page, 'rollback failed')).toBeVisible()
  await page.getByLabel('Outcome summary / rollback reason').fill('Failure reviewed. Recovery remains unresolved.')
  await page.getByRole('button', { name: 'Record recovery', exact: true }).click()
  await page.getByRole('dialog', { name: 'Record this recovery outcome?' }).getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(state(page, 'recovery required')).toBeVisible()
  await page.getByLabel('Outcome summary / rollback reason').fill('Recovery evidence reviewed and simulation closed.')
  await page.getByRole('combobox', { name: 'Recovery outcome', exact: true }).selectOption('resolved')
  await page.getByRole('button', { name: 'Record recovery', exact: true }).click()
  await page.getByRole('dialog', { name: 'Record this recovery outcome?' }).getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(state(page, 'recovered')).toBeVisible()
  await page.locator('[data-maintenance-content]').evaluate(element => { element.scrollTop = 0 })
  await page.getByRole('heading', { name: 'Maintenance', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('recovered.png'), animations: 'disabled' })
})

test('changed targets invalidate preview and require a fresh server read', async ({ page, sysApi: request }) => {
  await resetBrowserState(page)
  const asset = await createAsset(request, { name: `Maintenance stale ${Date.now()}`, system: 'UI readiness', type: 'Physical', status: 'Active' })
  const action = await recordAction(request, asset.id)
  await page.goto(`/monitoring?workspace=maintenance&action=${action.id}`)
  await page.getByRole('button', { name: 'Preview plan', exact: true }).click()
  await expect(state(page, 'previewed')).toBeVisible()
  expect((await request.put(`${apiBase}/devices/${asset.id}`, { data: { name: `${asset.name} changed` } })).ok()).toBeTruthy()
  await page.getByLabel('I reviewed this simulation, its targets, risk and recovery plan.').check()
  await page.getByRole('button', { name: 'Confirm reviewed plan', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Refresh the recorded state before continuing.' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Confirm reviewed plan', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Refresh recorded state', exact: true }).click()
  await expect(state(page, 'stale')).toBeVisible()
  await page.getByRole('button', { name: 'Refresh preview', exact: true }).click()
  await expect(state(page, 'previewed')).toBeVisible()
  await confirmPlan(page)
})

test('an uncertain plan save reuses its immutable request and draft departure is guarded', async ({ page, sysApi: request }) => {
  await resetBrowserState(page)
  const asset = await createAsset(request, { name: `Maintenance interrupted ${Date.now()}`, system: 'UI readiness', type: 'Physical', status: 'Active' })
  await page.goto(`/monitoring?workspace=maintenance&plan=new&device_id=${asset.id}`)
  await page.getByLabel('Plan title').fill('Recover this exact plan')
  await page.locator('#sg-main-content').getByRole('link', { name: 'Monitoring', exact: true }).click()
  const leave = page.getByRole('dialog', { name: 'Leave maintenance changes?' })
  await expect(leave).toBeVisible()
  await leave.getByRole('button', { name: 'Keep editing', exact: true }).click()
  await expect(leave).toHaveCount(0)
  await expect(page.getByLabel('Plan title')).toHaveValue('Recover this exact plan')
  const sent: Array<{ key: string | undefined; body: string | null }> = []
  await page.route('**/api/v1/operational-actions', async route => {
    if (route.request().method() !== 'POST') return route.continue()
    sent.push({ key: route.request().headers()['idempotency-key'], body: route.request().postData() })
    const response = await route.fetch()
    if (sent.length === 1) return route.abort('failed')
    await route.fulfill({ response })
  })
  await page.getByRole('button', { name: 'Save plan', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'The save outcome is unknown.' })).toBeVisible()
  await expect(page.getByLabel('Plan title')).toBeDisabled()
  await page.getByRole('button', { name: 'Recover saved plan', exact: true }).click()
  await expect(state(page, 'created')).toBeVisible()
  expect(sent).toHaveLength(2)
  expect(sent[1]).toEqual(sent[0])
  const history = await (await request.get(`${apiBase}/operational-actions?device_id=${asset.id}`)).json()
  expect(history).toHaveLength(1)
})

test('a late plan save does not reopen the action after the user leaves', async ({ page, sysApi: request }) => {
  await resetBrowserState(page)
  const asset = await createAsset(request, { name: `Maintenance late save ${Date.now()}`, system: 'UI readiness', type: 'Physical', status: 'Active' })
  await page.goto(`/monitoring?workspace=maintenance&plan=new&device_id=${asset.id}`)
  await page.getByLabel('Plan title').fill('Save without redirecting a later workspace')
  let release!: () => void
  const held = new Promise<void>(resolve => { release = resolve })
  let recorded!: () => void
  const serverRecorded = new Promise<void>(resolve => { recorded = resolve })
  await page.route('**/api/v1/operational-actions', async route => {
    if (route.request().method() !== 'POST') return route.continue()
    const response = await route.fetch()
    recorded()
    await held
    await route.fulfill({ response })
  })
  try {
    await page.getByRole('button', { name: 'Save plan', exact: true }).click()
    await serverRecorded
    await page.getByRole('button', { name: 'Action history', exact: true }).click()
    await page.getByRole('dialog', { name: 'Leave maintenance changes?' }).getByRole('button', { name: 'Discard and leave', exact: true }).click()
    await expect(page.getByRole('heading', { name: `Action history for asset #${asset.id}`, exact: true })).toBeVisible()
    const response = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/operational-actions'))
    release()
    await response
    await expect(page.getByRole('link', { name: /Save without redirecting a later workspace/ })).toBeVisible()
    expect(new URL(page.url()).searchParams.has('action')).toBe(false)
  } finally { release() }
})
